### ISSUE TITLE
Please add "Sign up with Google Account" option in github

### ISSUE THREAD

**Issue by Donboscow** [github/webauthn-json#12]
Add Sign up & Sign in with Google Account feature in github. I am missing this feature very badly.

**Comment by lgarron** [comment]
This repository is about an open-source project.

If you have a feature request for the GitHub site, I recommend getting in touch with GitHub support! 😊
https://support.github.com/

**Comment by Donboscow** [comment]
Can you please suggest this feature to your boss or colleague? They will take it seriously because you work at github! @lgarron
