### ISSUE TITLE
There seems to be no link to the "demo source" on the demo page

### ISSUE THREAD

**Issue by kg0r0** [github/webauthn-json#13]
It seems that the link of the "demo source" on the [demo page](https://github.github.com/webauthn-json/demo/) cannot be found.
Perhaps there is no link in the following line:
https://github.com/github/webauthn-json/blob/gh-pages/demo/index.html#L12
Could you check it?

**Comment by lgarron** [comment]
Thanks for noticing!

This was fixed in https://github.com/github/webauthn-json/pull/11 but I forgot to push an updated build of the demo site. I've gone ahead and done that in 9cc62e3430de2f72b0f25e45da9e9060bcfd644d!

**Comment by kg0r0** [comment]
Thank you for confirmation!
