### ISSUE TITLE
missing keys?

### ISSUE THREAD

**Issue by Arvanaghi** [github/webauthn-json#18]
EDIT: Resolved

**Comment by gregbenner** [comment]
I think it's related but 
```js
user: { 
                id: "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII", 
                name: "test_user", 
                displayName: "Test User" 
            },
```

This whole pojo doesn't seem to be stored in the localStorage or used in any way?

**Comment by Arvanaghi** [comment]
@gregbenner Those are stored on the authenticator itself. It does not need to be saved in localstorage.

**Comment by gregbenner** [comment]
@Arvanaghi the authenticator as in the U2F key?
