### ISSUE TITLE
Unable to import createExtended() and getExtended() methods from webauthn-json/extended

### ISSUE THREAD

**Issue by santiagorodriguez96** [github/webauthn-json#20]
Hi there! Thank you for your work on this!

I'm trying to use the `createExtended()` and `getExtended()` methods, but I'm unable to import them using `import { createExtended, getExtended } from '@github/webauthn-json/extended'`.
I'm using version `0.4.1` of this package.
The error I'm getting is:

<img width="696" alt="Screen Shot 2020-06-03 at 2 38 40 PM" src="https://user-images.githubusercontent.com/46354312/83669418-f19de600-a5a7-11ea-804f-8f4b2aa552ca.png">

According to the documentation importing from `@github/webauthn-json/extended` should work but it seems that this file does not exist in `node_modules` after installing the last version.

**Comment by lgarron** [comment]
Ah, good catch — the build files are actually in `@github/webauthn-json/dist/extended`.

**Comment by lgarron** [comment]
Thanks for the report!

**Comment by santiagorodriguez96** [comment]
Hey man thanks for the response! Unfortunately, I tested it but it still doesn't work 😕 😓 

![Screen Shot 2020-06-12 at 10 28 04 AM](https://user-images.githubusercontent.com/46354312/84511026-51794880-ac9c-11ea-9c4c-1fb2557960bb.png)

**Comment by lgarron** [comment]
Woah, it looks like `v0.4.1` was never actually published to the public `npm` registry.

We dual-publish packages to both the public `npm` registry and the GitHub registry (https://github.com/github/webauthn-json/packages/18707/versions) but it seems something is going wrong and the `npm` publication fails. I've hacked a `v0.4.2` release for now, which seems to have the files: https://unpkg.com/browse/@github/webauthn-json@0.4.2/dist/

Out of curiosity, which extended fields are you looking to use? This is the first I've hear of anyone trying to use them, so it's good to know that there's actually some interest in that build.

**Comment by santiagorodriguez96** [comment]
Great! It worked! Now I'm able to import the extension using version `0.4.2` and `import { getExtended } from "@github/webauthn-json/dist/extended.esm"` – the other option specified in the documentation was raising: `TypeError: "Object(...) is not a function"` when calling `getExtended`. To give a little more context, I'm calling `getExtended` like:

```javascript
getExtended({ "publicKey": credentialOptions }).then(function(credential) { ... }).catch(function(error) { ... });
```

with `credentialOptions` being:

<img width="332" alt="Screen Shot 2020-06-15 at 12 29 59 PM" src="https://user-images.githubusercontent.com/46354312/84677007-825bb680-af04-11ea-89bd-b41ca14f6ae8.png">

> Out of curiosity, which extensions are you looking to use? This is the first I've heard of anyone trying to use them, so it's good to know that there's actually some interest in that build.

Currently, I'm trying to implement a new feature in the [webauthn-ruby](https://github.com/cedarcode/webauthn-ruby) gem for [providing the extension outputs](https://github.com/cedarcode/webauthn-ruby/pull/317) so my intention was to test the extensions in the [webauthn rails demo app](https://github.com/cedarcode/webauthn-rails-demo-app). Currently I was using `txAuthSimple`.

Anyway, now I'm able to successfully authenticate using `getExtended` and passing the extension `txAuthSimple: "Could you please verify yourself?"` but it looks like the extension is being ignored given that nothing is being returned in `ClientExtensionResults` and also nothing is being displayed by the authenticator – which should happen [according to the documentation](https://www.w3.org/TR/webauthn-2/#sctn-generic-txauth-extension) 😕  

Is there something that I should be doing different?

**Comment by bdewater** [comment]
I think it's because no browser implemented this extensions, a lot were removed from the spec: https://github.com/w3c/webauthn/issues/1386

**Comment by santiagorodriguez96** [comment]
Oh I see! That makes sense 😅
