### ISSUE TITLE
Not getting "clientExtensionResults" key in the output of get() and create() methods

### ISSUE THREAD

**Issue by santiagorodriguez96** [github/webauthn-json#23]
Hi there!

In the documentation, it states that:

>Modern browsers generally only support a single extension: the appid string. If you need to convert additional input or output extensions, use createExtended() and getExtended() from @github/webauthn-json/dist/extended (or @github/webauthn-json/dist/extended.esm).

So, If I understood correctly, I should be able to use the `appid` extension with the default `create()` and `get()` methods.

However, when I pass the extension in the credential options to those methods, I don't get the `clientExtensionResults` in the output.

I can go ahead and try to make it that `clientExtensionResults` are returned just as it's done for the `extended` module If you agree with this 🙂

**Comment by ensurity-dev** [comment]
We are also facing issue with empty clientExtensionResults after usage
