### ISSUE TITLE
Include rollup in releases

### ISSUE THREAD

**Issue by Piccirello** [github/webauthn-json#24]
It would be helpful if the `dist/` directory created by rollup were included in each release. Currently, I have to run `rollup` manually after each release.

**Comment by lgarron** [comment]
Which version are you using? I think I had an issue before, but the latest release seems to have a dist dir:

- I get a `dist` dir locally with `npm install @github/webauthn-json`.
- https://unpkg.com/browse/@github/webauthn-json@0.4.2/dist/ shows it.

**Comment by lgarron** [comment]
@Piccirello Do you have any more info? As far as I can tell, the published package already includes what you're asking for, so I'm not sure I can do anything helpful.

**Comment by Piccirello** [comment]
I'm using the releases uploaded to GitHub Releases. Those don't seem to have a `dist/` folder, including the latest v0.4.5.

**Comment by lgarron** [comment]
Ah, you mean at https://github.com/github/webauthn-json/releases ? Those downloads only include the source code, and normal practice is not to include the builds in the source code itself.

I recommend using `npm` to manage your dependencies if you can. Otherwise, the package package at https://github.com/github/webauthn-json/packages/18707 should give you the download you want!

**Comment by Piccirello** [comment]
> The download links on those pages only include the source code, and normal practice is not to include the builds in the source code itself.

That seems like a strange distinction to me. Why call it a "release" if it doesn't match the files that you release via package managers?

**Comment by lgarron** [comment]
> > The download links on those pages only include the source code, and normal practice is not to include the builds in the source code itself.
> 
> That seems like a strange distinction to me. Why call it a "release" if it doesn't match the files that you release via package managers?

This is how the Releases feature works on GitHub — tags can automatically be converted into releases, and the source code links are added by GitHub. It may not be very intuitive in all cases, but that's how it works right now.

The appropriate place to get the code is `npm` (or the GitHub Package Registry), so we don't have any plans to change how this repo is managed.

The only thing we could do to reduce the risk of confusion is avoid showing release tags in the side bar, but that makes it harder to manage or review releases.

**Comment by cuu508** [comment]
> I recommend using npm to manage your dependencies if you can. Otherwise, the package package at https://github.com/github/webauthn-json/packages/18707 should give you the download you want!

Is there a build/version of this library, that can be used the old-fashioned-way, by downloading a JS file, dropping it in the static files directory, and including in HTML using the `<script>` tag, without using npm?

**Comment by lgarron** [comment]
> > I recommend using npm to manage your dependencies if you can. Otherwise, the package package at https://github.com/github/webauthn-json/packages/18707 should give you the download you want!
> 
> Is there a build/version of this library, that can be used the old-fashioned-way, by downloading a JS file, dropping it in the static files directory, and including in HTML using the `<script>` tag, without using npm?

Do either of these work for you?

https://github.com/github/webauthn-json/issues/24#issuecomment-655850191
https://github.com/github/webauthn-json/issues/24#issuecomment-659016896

If not, you can also try: https://registry.npmjs.org/@github/webauthn-json/-/webauthn-json-0.5.7.tgz

**Comment by cuu508** [comment]
`webauthn-json.browser-global.js` is what I was looking for, thanks @lgarron!

**Comment by cuu508** [comment]
Hello, I'm looking at `webauthn-json.browser-global.js` from recent releases. Starting from 0.6.x versions, it looks quite different from the one in 0.5.7. It defines a bunch of functions at the root namespace. So, unless I'm missing something (quite possible!), it is not suitable for being directly referenced from a HTML file, as it would pollute the root namespace. 

To recap, what I want is to use webauthn-json the old-fashioned-way, by downloading a JS file, dropping it in the static files directory, and including in HTML using the <script> tag. No build process. Is that possible?

**Comment by cuu508** [comment]
If I edit build-js.js and change the format here:

https://github.com/github/webauthn-json/blob/3e50ace50c0dd918c6149b1c62d67029b3f8e39c/script/build-js.js#L44

from "cjs" to "iife", and rebuild, the resulting `webauthn-json.browser-global.js` looks more browser-friendly, although I haven't tried to use it yet.

esbuild docs say `cjs` (CommonJS) output is intended to be used in node, whereas `iife` output is intended for web browsers so that lines up.
