### ISSUE TITLE
Unable to authenticate credentials using getExtended

### ISSUE THREAD

**Issue by santiagorodriguez96** [github/webauthn-json#26]
After updating to version v0.4.5, I'm unable to authenticate credentials using the extended module, getting the following error:

![Screen Shot 2020-07-30 at 2 07 09 PM](https://user-images.githubusercontent.com/46354312/88954495-e0ecb200-d270-11ea-9926-5d31d7b5c7dc.png)

It works correctly with the method `get` from the default module though.

**Comment by lgarron** [comment]
Would you mind providing a more thorough example for this?

**Comment by lgarron** [comment]
Woah, I just realized that the build *is* using the wrong schema, thanks for filing this!

**Comment by lgarron** [comment]
Please try the fix in `v0.5.3`!

**Comment by santiagorodriguez96** [comment]
>Please try the fix in v0.5.3!

Great! Seems to be working fine! 
However still have to test the `appExclude` extension when using the extended module as I don't have a U2F key with me right now, but for sure I'll do it when I have one.
