### ISSUE TITLE
Webpack bundling broken after version 0.5.0

### ISSUE THREAD

**Issue by Rowno** [github/webauthn-json#30]
Bundling `@github/webauthn-json` in a Webpack project broke in version 0.5.0. I'm guessing related to the Parcel 2 change. The following error is thrown when trying to import `@github/webauthn-json`.

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ~/projects/test/node_modules/@github/webauthn-json/dist/main/webauthn-json.js
require() of ES modules is not supported.
require() of ~/projects/test/node_modules/@github/webauthn-json/dist/main/webauthn-json.js from ~/projects/test/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename webauthn-json.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ~/projects/test/node_modules/@github/webauthn-json/package.json.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1154:13)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack-internal:///@github/webauthn-json:1:18)
    at Object.@github/webauthn-json (~/projects/test/.next/server/pages/index.js:175:1)
    at __webpack_require__ (~/projects/test/.next/server/pages/index.js:23:31)
    at eval (webpack-internal:///./src/client/register.ts:3:79)
    at Module../src/client/register.ts (~/projects/test/.next/server/pages/index.js:152:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by lgarron** [comment]
> Bundling `@github/webauthn-json` in a Webpack project broke in version 0.5.0. I'm guessing related to the Parcel 2 change.

Yeah, we now publish only publish ES module builds for GitHub packages (hence the `"type": "module"` part of the error). This project started doing that at the same time as the Parcel 2 change.

We don't plan to re-introduce other builds (e.g. CJS, UMD), so you'll have to update your bundler set up to handle ESM directly. I'll leave this open for a bit, so we can track if you got it working or ran into another issue.

**Comment by Rowno** [comment]
Turns out that the Next.js server-side build breaks when a package only contains ES modules:
https://github.com/vercel/next.js/issues/6369
https://github.com/vercel/next.js/issues/9607

This is because they disable all parsing and bundling of `node_modules` for the server-side build in order to speed up build times and reduce the size of the server build. This doesn't affect packages that ship both ES module and CommonJS entrypoints because Webpack will automatically use the ES module entrypoint for the client-side build and Node.js will use the CommonJS entrypoint when running the server-side build.

However I was able to workaround the issue by using [next-transpile-modules](https://github.com/martpie/next-transpile-modules) to transpile `@github/webauthn-json` using Babel. The downside of this is that it disables tree shaking for the package, but since `@github/webauthn-json` is a pretty tiny package it isn't a big deal.

**Comment by lgarron** [comment]
> However I was able to workaround the issue by using [next-transpile-modules](https://github.com/martpie/next-transpile-modules) to transpile `@github/webauthn-json` using Babel. The downside of this is that it disables tree shaking for the package, but since `@github/webauthn-json` is a pretty tiny package it isn't a big deal.

Thanks, that's good to know. I'll close this issue for now, but we can reference this if more people run into significant issues.
