### ISSUE TITLE
type export in version 0.6

### ISSUE THREAD

**Issue by dartess** [github/webauthn-json#52]
In version 0.5 we used
```
import {
  PublicKeyCredentialDescriptorJSON,
  PublicKeyCredentialWithAssertionJSON,
  PublicKeyCredentialWithAttestationJSON,
} from '@github/webauthn-json';
```

After upgrading to 0.6, the last two types were found along a different path: `@github/webauthn-json/extended`. 

The third type `PublicKeyCredentialDescriptorJSON` is only exported from `@github/webauthn-json/dist/types/basic/json`, which looks wrong.

Is this type not meant to be accessed externally, or is there something wrong in the type declaration?

**Comment by lgarron** [comment]
> Is this type not meant to be accessed externally, or is there something wrong in the type declaration?

Hmm, I thought the old `@github/webauthn-json` type exports didn't include these types, so I didn't try to preserve them for `v0.6`. Looks like I was wrong about that, so I'll see about getting those restored.

**Comment by lgarron** [comment]
Alright, please let me know if `v0.6.4` works for you!

**Comment by dartess** [comment]
@lgarron updated successfully, thanks!

**Comment by kubijo** [comment]
@lgarron would you please, while we are at the topic of exports, consider also exporting the functions for conversion between typed array and json?

I am mocking the browser APIs in our storybook and to show an application modal with response options instead of the native thing (which wouldn't work) and to achieve it I had to copy over your code to our lib.

**Comment by lgarron** [comment]
> @lgarron would you please, while we are at the topic of exports, consider also exporting the functions for conversion between typed array and json?

We already do that!

https://github.com/github/webauthn-json/blob/15ff87cf298571365bfc540c3c6553f65bdb5ce6/src/webauthn-json/extended.ts#L21-L28

Does that work for you?

**Comment by kubijo** [comment]
Damn, I must have misted it in the versions that had glitches
