### ISSUE TITLE
Bundling errors under yarn3 after upgrade from `0.5.7` to `0.6.2`

### ISSUE THREAD

**Issue by kubijo** [github/webauthn-json#53]
```bash
$ yarn dlx -q envinfo --preset jest

  System:
    OS: Linux 5.11 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 16.13.1 - /tmp/xfs-705ba6ea/node
    Yarn: 3.2.0-rc.5 - /tmp/xfs-705ba6ea/yarn
```

```
$ yarn why @github/webauthn-json
└─ xxx@packages/xxx
   └─ @github/webauthn-json@npm:0.6.2 (via npm:0.6.2)
```

```
webpack@npm:5.66.0
typescript@patch:typescript@npm%3A4.5.4#~builtin<compat/typescript>::version=4.5.4&hash=493e53
```

<pre><span color="#CC0000"><b>ERROR</b></span> in <b>./packages/xxx/lib/fido.tsx</b> <span color="#4E9A06"><b>17:0-46</b></span>
<b>Module </b><span color="#CC0000"><b>not found</b></span><b>: </b><span color="#CC0000"><b>Error</b></span><b>: Can&apos;t resolve &apos;@github/webauthn-json&apos; in &apos;/path/to/packages/xxx/lib&apos;</b>
resolve &apos;@github/webauthn-json&apos; in &apos;/path/to/packages/xxx/lib&apos;
  Parsed request is a module
  using description file: /path/to/packages/xxx/package.json (relative path: ./lib)
    Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
    resolve as module
      resolved by pnp to /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/
        using description file: /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/package.json (relative path: .)
          using exports field: ./dist/webauthn-json.js
            using description file: /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/package.json (relative path: ./dist/webauthn-json.js)
              no extension
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js doesn&apos;t exist</b></span>
              .ts
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.ts doesn&apos;t exist</b></span>
              .tsx
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.tsx doesn&apos;t exist</b></span>
              .js
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.js doesn&apos;t exist</b></span>
              .mjs
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.mjs doesn&apos;t exist</b></span>
              .cjs
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.cjs doesn&apos;t exist</b></span>
              .ejs
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.ejs doesn&apos;t exist</b></span>
              .jsx
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.jsx doesn&apos;t exist</b></span>
              .json
                Field &apos;browser&apos; doesn&apos;t contain a valid alias configuration
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js.json doesn&apos;t exist</b></span>
              as directory
<span color="#CC0000"><b>                /path/to/.yarn/cache/@github-webauthn-json-npm-0.6.2-4bf1caaf04-a10c7a9e5a.zip/node_modules/@github/webauthn-json/dist/webauthn-json.js doesn&apos;t exist</b></span>
</pre>

**Comment by lgarron** [comment]
Do you have documentation on what `yarn` expects?

We only have one main build, and it's listed as [`main`](https://github.com/github/webauthn-json/blob/c5ba194c026fc557645a0f29a154e5a3c4b71887/package.json#L9) as well as in [`exports`](https://github.com/github/webauthn-json/blob/c5ba194c026fc557645a0f29a154e5a3c4b71887/package.json#L12-L21).

**Comment by kubijo** [comment]
Nope... Given that I have not yet worked on any package distributed on NPM, I can't say much from the top of my head.

- Their docs are however very good
- It generally doesn't require anything specific, but enforces good standards that other package managers only recommend...
- and @arcanis is always very helpful should there be a problem with yarn in the end...

**Comment by arcanis** [comment]
The `exports` field in https://cdn.jsdelivr.net/npm/@github/webauthn-json@0.6.4/package.json references an invalid file (presumably you forgot the `esm` folder in `./dist/webauthn-json.js`, same for `./dist/webauthn-json.extended.js`).

**Comment by dartess** [comment]
Same problem without using yarn.
Webpack build fails to resolve the dependency.

**Comment by lgarron** [comment]
> The `exports` field in https://cdn.jsdelivr.net/npm/@github/webauthn-json@0.6.4/package.json references an invalid file (presumably you forgot the `esm` folder in `./dist/webauthn-json.js`, same for `./dist/webauthn-json.extended.js`).

Aha! Thanks, that would explain it. This kind of stuff makes me really grumbly that this still needs to be done by hand. 😆

**Comment by lgarron** [comment]
Alright, please let me know if `v0.6.5` works for you!

**Comment by dartess** [comment]
in my case everything worked. thanks!

**Comment by kubijo** [comment]
Yep, working fine :+1:
