### ISSUE TITLE
Broken link to example in REAMDE.md

### ISSUE THREAD

**Issue by dartess** [github/webauthn-json#54]
https://github.com/github/webauthn-json/blob/main/README.md#:~:text=See%20here%20for%20fully%20working%20client%2Dside%20demo%20code.

https://github.com/github/webauthn-json/blob/main/src/targets/demo/index.ts

**Comment by lgarron** [comment]
Yeah, I need to get around to building that with Actions.

https://github.com/github/webauthn-json/issues/51
