### ISSUE TITLE
Expose resident key options

### ISSUE THREAD

**Issue by bdewater** [github/webauthn-json#6]
Thank you for your work!

While reading the source I noticed there was nothing for resident keys available, either
- `residentKey` which is the newer enum available in level 2, or 
- `requireResidentKey` which is the older boolean

Exposing these is necessary for username- and passwordless login. For more information: https://www.w3.org/TR/webauthn-2/#dictdef-authenticatorselectioncriteria

**Comment by lgarron** [comment]
Those particular strings don't appear in the source code here because we copy the entire the `authenticatorSelection` field: https://github.com/github/webauthn-json/blob/master/src/webauthn-schema.ts#L28

Have you run into actual issues trying to use those values?

**Comment by bdewater** [comment]
Ah, my bad! Have not used it yet but was evaluating it :) thanks!
