### ISSUE TITLE
Usage of this library with Flask

### ISSUE THREAD

**Issue by Artur-Galstyan** [github/webauthn-json#64]
Hi there!

I want to use this library with Flask, but I am unable to do so. Could you give a minimum viable example of how to include this library if one wasn’t using Typescript or Node JS? 

Essentially, I want to be able to use this library in a single html file with a script tag in there. But after several hours of trying, I couldn’t figure it out. 

Any help?

**Comment by lgarron** [comment]
> Essentially, I want to be able to use this library in a single html file with a script tag in there.

Does the example help?
https://github.com/github/webauthn-json/blob/main/src/dev/demo/index.ts

--------

As far as I can tell, you're referring to the Python project Flask. This library predates most backend libraries and we only use Ruby, so unfortunately we're not equipped to provide advice on Python backend implementation details.

However, @masterkale maintains https://github.com/duo-labs/py_webauthn , which may work for you.

**Comment by MasterKale** [comment]
@Artur-Galstyan You can get started with a template as simple as this which uses this project's UMD build:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script
    src="https://unpkg.com/@github/webauthn-json@2.0.0-alpha4/dist/browser-global/webauthn-json.browser-global.js"
    integrity="sha384-KpXiQogRMy9zGl2pk218HI3w/hStndlWnUnMHWejGsg7Nx0Gf2NS+3kuN1vAQwjA"
    crossorigin="anonymous"
  ></script>
  <title>@github/webauthn-json</title>
</head>
<body>
  <script>
    const { supported } = webauthnJSON;

    alert(`WebAuthn supported: ${supported()}`);
  </script>
</body>
</html>
```

If you're only targeting evergreen (i.e. modern) browsers you can leverage the ES modules build within `<script type="module">` tags for something more streamlined:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@github/webauthn-json</title>
</head>
<body>
  <script type="module">
    import { supported } from 'https://unpkg.com/@github/webauthn-json@2.0.0-alpha4/dist/esm/webauthn-json.js';
    
    alert(`WebAuthn supported: ${supported()}`);
  </script>
</body>
</html>
```

**Comment by Artur-Galstyan** [comment]
Thanks for your replies, I will give that a try and then close this issue if I succeed 👍
