### ISSUE TITLE
How can I access the attestationObject?

### ISSUE THREAD

**Issue by drewcapener** [github/webauthn-json#66]
Sorry if this is straightforward and I've missed the explanation in the documentation, but I am unsure how to decode the attestationObject on my server. I was able to decode the clientDataObject with `Buffer.from(credential.response.clientDataJSON, 'base64url').toString('ascii')` but the same doesn't seem to work with the attestationObject. It appears the attestationObject is also CBOR encoded. So, I tried decoding from base64url and then from CBOR but that didn't work. Anyway, I'd appreciate any help I can get here. Thanks in advance!

**Comment by lgarron** [comment]
This library is only for JS clients, so I can't really be of much help.

You might find some the libraries listed at https://webauthn.io/ helpful.

If you want a single library that also provides server functionality, you may want to consider https://github.com/MasterKale/SimpleWebAuthn as well.

**Comment by lgarron** [comment]
Closing this for now; let us know if you have more issues.
