### ISSUE TITLE
Support "hybrid" transport type

### ISSUE THREAD

**Issue by jessejacksonafterpay** [github/webauthn-json#67]
The transport type "hybrid" is now officially part of the spec, so would be great if this was supported in the enum type.

https://github.com/w3c/webauthn/commit/656e61356345c709292b6b2fcaaff7a57a82bf33

**Comment by lgarron** [comment]
The `AuthenticatorTransport` type definition comes from `lib.dom.d.ts`. However, we *can* extend that easily without changing the runtime code, so I'd be in facor.
