### ISSUE TITLE
Cannot get Face ID option in IOS Safari

### ISSUE THREAD

**Issue by amohammed96** [github/webauthn-json#70]
Hi,

When I run the demo on IOS Safari and click register, safari shows a pop-up
"Do you want to allow "github.github.com" to use Face ID?"

But when I try the same option on my website it shows
"Do you want to save a passkey for "test"?

furthermore, in your demo when I click "Other Options"
It shows the first option as Face ID.
On my website, it shows "Passkey in iCloud Keychain.

I did not recognize the difference in your demo. to show Face ID option.

**Comment by lgarron** [comment]
Responded via email.
