### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by hiniestic** [github/webauthn-json#78]
I'm getting:
 ERROR in node_modules/@github/webauthn-json/dist/types/basic/api.d.ts(2,92): error TS2304: Cannot find name 'CredentialCreationOptions'.
|     node_modules/@github/webauthn-json/dist/types/basic/api.d.ts(3,58): error TS2304: Cannot find name 'PublicKeyCredential'.
|     node_modules/@github/webauthn-json/dist/types/basic/api.d.ts(5,88): error TS2304: Cannot find name 'CredentialRequestOptions'.

And also:
ERROR in ../node_modules/@github/webauthn-json/dist/types/browser-ponyfill.d.ts:5:1 - error TS1128: Declaration or statement expected.

**Comment by lgarron** [comment]
The errors seem to suggest that your environment doesn't have the ambient TypeScript declarations from `lib.doom.d.ts`. Could I ask which version of TypeScript you're using, and how?

**Comment by hiniestic** [comment]
I'm using and old project on angular 7 with typescript 3.5.3. Do you know the min version needed?
Thanks!

**Comment by lgarron** [comment]
> Do you know the min version needed?

I did some testing, and TypeScript 3.8 should work for now. But I'd still recommend updating to the most recent version you can.
