### ISSUE TITLE
Export `PublicKeyCredentialRequestOptionsJSON`

### ISSUE THREAD

**Issue by dartess** [github/webauthn-json#86]
Please add export type `PublicKeyCredentialRequestOptionsJSON`, we prepare it using a separate method.

**Comment by lgarron** [comment]
I think you're looking for `CredentialRequestOptionsJSON`?

```ts
import { type CredentialRequestOptionsJSON, get, create } from "@github/webauthn-json";

const r: CredentialRequestOptionsJSON = {
	/* … */
} as CredentialRequestOptionsJSON;
console.log(await get(r));
```

**Comment by dartess** [comment]
No, but I was a little hasty in the code review and didn’t get into the code. We just used `CredentialRequestOptionsJSON['publicKey']` instead of `PublicKeyCredentialRequestOptionsJSON`. Sorry! 🙏

**Comment by lgarron** [comment]
> We just used `CredentialRequestOptionsJSON['publicKey']` instead of `PublicKeyCredentialRequestOptionsJSON`.

Yeah, this is the way to get the type of a field if you really need. Glad it worked out for you!
