### ISSUE TITLE
Is it possible to change the design of the popup? 

### ISSUE THREAD

**Issue by WatameBytes** [github/webauthn-json#92]
Quick question, I don't really like how the popup looks when it calls the .create()/.get() method and was wondering if it is possible to modify the style in any way?

I feel like given this is a wrapper, this may not be the right place to ask, but it doesn't hurt to ask to see if this is even possible or not.

**Comment by WatameBytes** [comment]
I'm 99% sure the answer is no

**Comment by lgarron** [comment]
No, that's subject to the platform. There are discussions like https://github.com/w3c/webauthn/issues/1823 regularly but right now the RP has very little control.

**Comment by WatameBytes** [comment]
Thank you
